# Generated by Django 3.0.7 on 2020-06-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200615_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscritions',
            new_name='subscriptions',
        ),
    ]
