# Generated by Django 3.0.7 on 2020-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, help_text='In Euros (€)', max_digits=14),
        ),
    ]
