# Generated by Django 3.0.7 on 2020-06-23 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='This is pre-populated by the title', unique=True)),
                ('author', models.CharField(default='Conceição Cabral', max_length=100)),
                ('body', models.TextField(blank=True, max_length=1000, null=True)),
                ('photo_1', models.ImageField(upload_to='blog/photos/%Y/%m/%d', verbose_name='Main Photo')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='blog/photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='blog/photos/%Y/%m/%d')),
                ('written_at', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
    ]
