# Generated by Django 3.0.7 on 2020-06-15 17:07

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('photo_1', models.ImageField(upload_to='kits/photos/%Y/%m/%d', verbose_name='Main Photo')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='kits/photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='kits/photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='kits/photos/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='kits/photos/%Y/%m/%d')),
                ('products', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_kits.Category')),
            ],
        ),
    ]
