# Generated by Django 3.0.7 on 2020-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_kits', '0002_auto_20200615_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='new_member_stock',
            field=models.IntegerField(default=50),
        ),
    ]
