# Generated by Django 3.0.7 on 2020-06-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diameter_unit',
            field=models.CharField(blank=True, choices=[('', 'Select Unit'), ('m', 'Meter'), ('dm', 'Decimeter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inches')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('', 'Select Unit'), ('m', 'Meter'), ('dm', 'Decimeter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inches')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_unit',
            field=models.CharField(blank=True, choices=[('', 'Select Unit'), ('m', 'Meter'), ('dm', 'Decimeter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inches')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound')], default='kg', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_unit',
            field=models.CharField(blank=True, choices=[('', 'Select Unit'), ('m', 'Meter'), ('dm', 'Decimeter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inches')], default='', max_length=2),
        ),
    ]
